// Auto-generated by scripts/fetch-prices.mjs — do not edit manually
// Last updated: 2026-07-16T08:20:44.020Z

export interface SoftkeyProduct {
  id: string;
  nombre: string;
  precio: string;
  categoria: string;
  iconoId: string;
  iconoColor: string;
}

// Price overrides for hardcoded products
export const softkeyPrices: Record<string, string> = {
};

// Product IDs that require a softkey price override to be available
export const softkeyMappedIds: string[] = [
];

// Full product catalog from softkeypc.com
export const softkeyCatalog: SoftkeyProduct[] = [
];
